### ISSUE TITLE
[BUG]  MatFormioModule is not a reference: [object Object]

### ISSUE THREAD

**Issue by kenobi-io** [formio/angular-material#159]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework:
- Browser:
- Browser version:

## Steps to Reproduce
node_modules/angular-material-formio/fesm2015/angular-material-formio.js:4104:26 - error NG at position 4 in the NgModule.imports of MatFormioModule is not a reference: [object Object]
## Example
For code or form JSON, please enclose in a code block:

```js
node_modules/angular-material-formio/fesm2015/angular-material-formio.js:4104:26 - error NG at position 4 in the NgModule.imports of MatFormioModule is not a reference: [object Object]
[ng] 4104                 imports: [
[ng]                               ~
[ng] 4105                     CommonModule,
[ng]      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng]  ...
[ng] 4128                     DragDropModule
[ng]      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ng] 4129                 ],
[ng]      ~~~~~~~~~~~~~~~~~
```

**Comment by travist** [comment]
What version of Angular are you trying here?

**Comment by aca-pulco** [comment]
angular 11.0.0

**Comment by travist** [comment]
I would like to hold off on answering this one until we update this library to the latest angular releases.

**Comment by mdesens** [comment]
Instead of:

import {
  MatInputModule,
  MatButtonModule,
  MatFormFieldModule,
  MatCheckboxModule,
  MatRadioModule,
  MatSelectModule,
  MatListModule,
  MatChipsModule,
  MatExpansionModule,
  MatCardModule,
  MatStepperModule,
  MatTabsModule,
  MatTableModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatProgressSpinnerModule,
  MatIconModule,
  MatTooltipModule, MatMenuModule
} from '@angular/material';


Try this:

import { MatTableDataSource } from '@angular/material/table';
import { MAT_INPUT_VALUE_ACCESSOR } from '@angular/material/input';
import { MatInputModule } from '@angular/material/input';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatCheckboxModule } from '@angular/material/checkbox';
import { MatRadioModule } from '@angular/material/radio';
import { MatSelectModule } from '@angular/material/select';
import { MatListModule } from '@angular/material/list';
import { MatChipsModule } from '@angular/material/chips';
import { MatExpansionModule } from '@angular/material/expansion';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatStepperModule } from '@angular/material/stepper';
import { MatTabsModule } from '@angular/material/tabs';
import { MatTableModule } from '@angular/material/table';
import { MatNativeDateModule } from '@angular/material/core';
import { MatDatepickerModule } from '@angular/material/datepicker';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatTooltipModule } from '@angular/material/tooltip';
import { MatIconModule } from '@angular/material/icon';
import { MatMenuModule } from '@angular/material/menu';

**Comment by SergioASalazarGastelo** [comment]
Any news about this? Thanks in advanced.

**Comment by travist** [comment]
I am hoping to work on an updated build for latest Angular versions this week.
